//    "start": "node scripts/start.js",
//    "build": "node scripts/build.js",
//    "test": "node scripts/test.js",
"start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",